// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: payment.proto

package grpc;

public interface CardOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Card)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 userId = 1;</code>
   * @return The userId.
   */
  int getUserId();

  /**
   * <code>int32 amount = 2;</code>
   * @return The amount.
   */
  int getAmount();
}
